### ISSUE TITLE
Ruta del query incorrecta

### ISSUE THREAD

**Issue by evaristor** [IslasGECI/queries#3]
El _script_ `cambia_formato_fecha` busca el _query_ en la ruta `src/` y no lo encuentra, pues está en `/usr/local/bin/`.

**Comment by nepito** [comment]
@MaritzaB tratemos mañana de cerrar este _issues_ aprovechando que no hay artículo de divulgación.

**Comment by evaristor** [comment]
Quedó resuelto en #4
